#!/usr/bin/env sh

beacon_node \
  --network=medalla \
  --log-level="DEBUG" \
  --log-file={{ nimbus_data_dir }}/log/nbc_bn.log \
  --data-dir={{ nimbus_data_dir }} \
  --web3-url={{ web3_url }} \
  --tcp-port=9000 \
  --udp-port=9000 \
  --metrics \
  --metrics-port=8008 \
  --rpc \
  --rpc-port=9190 \
  --nat="extip:{{ external_ip }}"
