- hosts: all
  become: true
  vars:
    device: "{{ lookup('env', 'STORAGE_DEVICE_ID') }}"
    opts: discard,defaults,noatime
    path: /var/nimbus-storage
  tasks:
    - name: Create a primary partition
      tags:
        - partition
      parted:
        device: "{{ device }}"
        number: 1
        state: present
        label: gpt
        part_type: primary
        part_start: "0%"
        part_end: "100%"
        unit: MiB

    - name: Create an EXT4 filesystem
      tags:
        - partition
      filesystem:
        fstype: ext4
        dev: "{{ device }}"

    - name: Mount the storage
      tags:
        - mount
      mount:
        path: "{{ path }}"
        fstype: ext4
        src: "{{ device }}"
        opts: "{{ opts }}"
        passno: "0"
        state: mounted
