#!/usr/bin/env sh

eth2stats-client run \
  --eth2stats.node-name="{{ nimbus_node_name }}" \
  --data.folder /var/eth2stats/data \
  --eth2stats.addr="grpc.pyrmont.eth2.wtf:8080" \
  --eth2stats.tls=false \
  --beacon.type="nimbus" \
  --beacon.addr="http://localhost:9190" \
  --beacon.metrics-addr="http://localhost:8008/metrics"
