#!/usr/bin/env sh

beacon_node \
  --network=medalla \
  --log-level="DEBUG" \
  --log-file=/var/nimbus/data/shared_medalla_0/nbc_bn_$(date +"%Y%m%d%H%M%S").log \
  --data-dir=/var/nimbus/data/shared_medalla_0 \
  --web3-url=wss://goerli.infura.io/ws/v3/809a18497dd74102b5f37d25aae3c85a \
  --tcp-port=9000 --udp-port=9000 --metrics --metrics-port=8008 --rpc --rpc-port=9190
