- hosts: all
  become: true
  vars:
    nimbus_network: "{{ lookup('env', 'NIMBUS_NETWORK') }}"
    nimbus_executable_name: nimbus_beacon_node
    nimbus_user: nimbus
    nimbus_data_dir: "/var/nimbus-storage/nimbus/data/shared_{{ nimbus_network }}_0"
    validator_keys_path: /var/nimbus-storage/nimbus/validator_keys
    web3_url: "{{ lookup('env', 'WEB3_URL') }}"
    external_ip: "{{ lookup('env', 'EXTERNAL_IP') }}"
    nimbus_release_url: "{{ lookup('env', 'NIMBUS_RELEASE_URL') }}"
    nimbus_release_folder: /tmp/nimbus
  tasks:
    - name: Create nimbus user
      tags:
        - setup
        - users
      user:
        name: "{{ nimbus_user }}"
        state: present
        append: true
        create_home: true
        shell: /bin/bash

    - name: Upload nimbus executable
      tags:
        - never
        - upload_exec
      copy:
        src: "../../build/{{ nimbus_executable_name }}"
        dest: /usr/bin/

    - name: Remove old release folder
      tags:
        - download_release
      file:
        state: absent
        path: "{{ nimbus_release_folder }}"

    - name: Re-create release folder
      tags:
        - download_release
      file:
        path: "{{ nimbus_release_folder }}"
        mode: "0750"
        state: directory
        owner: "{{ nimbus_user }}"
        group: "{{ nimbus_user }}"

    - name: Download nimbus release
      tags:
        - download_release
      get_url:
        url: "{{ nimbus_release_url }}"
        dest: "{{ nimbus_release_folder }}/nimbus.tgz"

    - name: Extract release archive
      tags:
        - download_release
      unarchive:
        remote_src: yes
        src: "{{ nimbus_release_folder }}/nimbus.tgz"
        dest: "{{ nimbus_release_folder }}"

    - name: Move release executable to /usr/bin
      tags:
        - download_release
      command: "sh -c 'mv {{ nimbus_release_folder }}/*/build/nimbus_beacon_node /usr/bin/{{ nimbus_executable_name }}'"

    # - name: Upload ncli_db executable
    #   tags:
    #     - never
    #     - upload_exec
    #   copy:
    #     src: ../../build/ncli_db
    #     dest: /usr/bin/

    - name: Upload run file
      tags:
        - setup
        - upload_exec
      template:
        src: nimbus_run
        dest: /usr/bin/

    - name: Fix beacon node executable permissions
      tags:
        - chmod
        - upload_exec
        - download_release
      file:
        dest: "/usr/bin/{{ nimbus_executable_name }}"
        mode: g+rx,o+rx

    # - name: Fix executable ncli_db permissions
    #   tags:
    #     - setup
    #     - chmod
    #     - upload_exec

      # file:
      #   dest: /usr/bin/ncli_db
      #   mode: g+rx,o+rx

    - name: Fix run file permissions
      tags:
        - setup
        - chmod
        - upload_exec
      file:
        dest: /usr/bin/nimbus_run
        mode: g+rx,o+rx

    - name: Create nimbus data folder
      tags:
        - setup
        - folders
        - upload_keys
      file:
        path: "{{ nimbus_data_dir }}"
        mode: "0750"
        state: directory
        owner: "{{ nimbus_user }}"
        group: "{{ nimbus_user }}"

    - name: Install nimbus unit files
      tags:
        - setup
        - systemd
      copy:
        src: "nimbus.service"
        dest: "/etc/systemd/system/nimbus.service"

    - name: Upload validator keys
      tags:
        - never
        - upload_keys
      copy:
        src: "../../assets/validator_keys"
        dest: "{{ validator_keys_path }}"
        owner: "{{ nimbus_user }}"
        group: "{{ nimbus_user }}"

    - name: Remove validator keys
      tags:
        - never
        - remove_keys
      file:
        state: absent
        path: "{{ validator_keys_path }}"

    - name: Setup logrotate
      tags:
        - setup
        - logrotate
      template:
        mode: u=rw,g=r,o=r
        src: logrotate.conf
        dest: "/etc/logrotate.d/nimbus"

    - name: Add cronjob for logrotate
      tags:
        - setup
        - logrotate
        - cron
      cron:
        name: "logrotate nimbus"
        minute: "0"
        hour: "*"
        job: "/usr/sbin/logrotate /etc/logrotate.d/nimbus --state {{ nimbus_data_dir }}/log/logrotate-state"
        user: "{{ nimbus_user }}"

    - name: Enable service nimbus
      tags:
        - systemd
        - run
        - restart
      systemd:
        name: nimbus
        state: restarted
        enabled: true
        daemon_reload: true
